name: Deploy to ISPmanager

on:
  push:
    branches:
      - main  # Укажите ветку для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка SSH для подключения к серверу
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH }}

      # Шаг 3: Выполнение git pull на сервере
      - name: Pull latest changes on server
        run: |
          # Настройка переменных
          SERVER_IP="147.45.237.94"
          USERNAME="root"
          REMOTE_PATH="/var/www/html/freelance"

          # Выполнение git pull на сервере
          ssh $USERNAME@$SERVER_IP << EOF
            cd $REMOTE_PATH || exit
            git pull origin main
          EOF
